u21429792_HW03/Models/FileModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace u21429792_HW03.Models
{
    public class FileModel
    {
        public string FileName { get; set; }
        public HttpPostedFileBase[] Files { get; set; }
    }

}

u21429792_HW03/Controllers/FileController.cs
using Microsoft.AspNetCore.Hosting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using u21429792_HW03.Models;

namespace u21429792_HW03.Controllers
{
    public class FileController : Controller
    {
      
        public ActionResult Files()
        {
            string[] filepaths = Directory.GetFiles(Server.MapPath("~/files/"));
            List<FileModel> files = new List<FileModel>();
            foreach (string filepath in filepaths)
            {
                files.Add(item: new FileModel { FileName = Path.GetFileName(filepath) });
            }
            return View(files);
        }

        public FileResult DownloadFile(string fileName)
        {
            string path = Server.MapPath("~/files/") + fileName;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", fileName);
        }

        public ActionResult DeleteFile(string fileName)
        {
            string path = Server.MapPath("~/files/") + fileName;
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            return RedirectToAction("Files");
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AboutMe()
        {

            return View();
        }

        public ActionResult Image()
        {
            return View();
        }

        public ActionResult Video()
        {
            return View();
        }
    }
}

u21429792_HW03/Controllers/HomeController.cs
using Microsoft.AspNetCore.Hosting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;
using u21429792_HW03.Models;

namespace u21429792_HW03.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Welcome to the media page.";


            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase files, string uploadType) //INSIDE HOME
        {
            // Verify that the user selected a file
            // Not null and has a length

            if (files != null && files.ContentLength > 0 && uploadType == "Document")
            {
                // extract only the filename

                var fileName = Path.GetFileName(files.FileName);

                // store the file inside ~/App_Data/uploads folder

                var path = Path.Combine(Server.MapPath("~/files/"), fileName);

                // The chosen default path for saving

                files.SaveAs(path);
            }
            else if (files != null && files.ContentLength > 0 && uploadType == "Image")
            {
                // extract only the filename

                var fileName = Path.GetFileName(files.FileName);

                // store the file inside ~/App_Data/uploads folder

                var path = Path.Combine(Server.MapPath("~/images/"), fileName);

                // The chosen default path for saving

                files.SaveAs(path);
            }
            // redirect back to the index action to show the form once again

            else if(files != null && files.ContentLength > 0 && uploadType == "Video")
            {
                // extract only the filename

                var fileName = Path.GetFileName(files.FileName);

                // store the file inside ~/App_Data/uploads folder

                var path = Path.Combine(Server.MapPath("~/videos/"), fileName);

                // The chosen default path for saving

                files.SaveAs(path);
            }
            return RedirectToAction("Index");
        }

    public ActionResult AboutMe()
        {

            return View();
        }

        public ActionResult Files()
        {
            return View();

        }

        public ActionResult Image()
        {
            return View();
        }

        public ActionResult Video()
        {
            return View();
        }
    } 
}

u21429792_HW03/Controllers/ImageController.cs
using Microsoft.AspNetCore.Hosting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using u21429792_HW03.Models;

namespace u21429792_HW03.Controllers
{
    public class ImageController : Controller
    {
        // GET: Image
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Image()
        {
            string[] filepaths = Directory.GetFiles(Server.MapPath("~/images/"));
            List<FileModel> images = new List<FileModel>();
            foreach (string filepath in filepaths)
            {
                images.Add(item: new FileModel { FileName = Path.GetFileName(filepath) });
            }
            return View(images);
        }

        public FileResult DownloadImage(string filename)
        {
            string path = Server.MapPath("~/images/") + filename;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", filename);
        }

        public ActionResult DeleteImage(string filename)
        {
            string path = Server.MapPath("~/images/") + filename;
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            return RedirectToAction("Image");
        }

        public ActionResult AboutMe()
        {

            return View();
        }

        public ActionResult Files()
        {
            return View();
        }

        public ActionResult Video()
        {
            return View();
        }
    }
}

u21429792_HW03/Controllers/VideoController.cs
using Microsoft.AspNetCore.Hosting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using u21429792_HW03.Models;

namespace u21429792_HW03.Controllers
{
    public class VideoController : Controller
    {
        // GET: Video
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Video()
        {
            string[] filepaths = Directory.GetFiles(Server.MapPath("~/videos/"));
            List<FileModel> videos = new List<FileModel>();
            foreach (string filepath in filepaths)
            {
                videos.Add(item: new FileModel { FileName = Path.GetFileName(filepath) });
            }
            return View(videos);
        }

        public FileResult DownloadVideo(string filename)
        {
            string path = Server.MapPath("~/videos/") + filename;
            byte[] bytes = System.IO.File.ReadAllBytes(path);

            return File(bytes, "application/octet-stream", filename);
        }

        public ActionResult DeleteVideo(string filename)
        {
            string path = Server.MapPath("~/videos/") + filename;
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            return RedirectToAction("Video");
        }

        public ActionResult AboutMe()
        {

            return View();
        }

        public ActionResult Files()
        {
            return View();
        }

        public ActionResult Image()
        {
            return View();
        }
    }
}

u21429792_HW03/Views/File/Files.cshtml
@using u21429792_HW03.Models
@model List<FileModel>


@{
    ViewBag.Title = "File Page";
}
<h2>@ViewBag.Title</h2>

<div>
    <table class="table table-responsive table-bordered" id="table">
        <tr>
            <th> File Name</th>
            <th> DOWNLOAD OPTION </th>
            <th> DELETE OPTION </th>
        </tr>
        @foreach (FileModel file in Model)
        {
            <tr>
                <td>@file.FileName</td>
                <td><button type="button" class="btn btn-success"> @Html.ActionLink("Download", "DownloadFile", new { fileName = file.FileName }) </button></td>
                <td><button type="button" class="btn btn-danger"> @Html.ActionLink("Delete", "DeleteFile", new { fileName = file.FileName }) </button></td>
            </tr>
        }
    </table>
</div>

u21429792_HW03/Views/Home/AboutMe.cshtml
@{
    ViewBag.Title = "About Me";
}
<h2>@ViewBag.Title</h2>


<div class="jumbotron">
    <div class="row">
        <div class="col-md-8">
            <h3>Description</h3>
            <p style="font-size:15px">
                I am a hard-working, dedicated person. I will always put my best effort into anything I do. <br/>
                I am a fast learner, and self-motivator. I’m a friendly, outgoing person, willing to help anywhere and whenever I am needed. <br />
                I enjoy spending time with family and doing family activities in our free time. <br />
                I am a very patient individual. I can work well with others because  <br />
                I am studying a BIT degree at University of Pretoria, full time. <br />
                I enjoy playing hockey to keep myself active, and in my relax time I enjoy watching and rewatching many different series. <br/>
                My favourite series are: Grey's Anatoymy, HIMYM, Full House, and Friends. <br/>
            </p>

        </div>

        <div class="col-md-4">
            <h3>Jenalle Davenall </h3>

            <img src="~/IMG_7691.jpg" width="240" height="300"/>

        </div>
    </div>
</div>

u21429792_HW03/Views/Home/Index.cshtml
@{
    ViewBag.Title = "My Media";
}
<h2>@ViewBag.Title</h2>
<h4>@ViewBag.Message</h4>

<div class="jumbotron">
    <div class="row">
        <div class="col-md-8">
            <h3>Description</h3>
            <p style="font-size:12px">
                For this assignment you will be creating a media uploading system. <br />
                Home page: The home page will have a form where users will need to select whether they want to upload a File, Image, or Video. Users will then be able to select the file on their computer which will then be uploaded on submit of the form. <br />
                Files page: The files page must display a list of all the Files that a user has uploaded with the functionality to delete and download the file. <br />
                Images page: The images page must display all the images (the images must be viewable) that the user uploaded, in an orderly way with the functionality to delete and download the images. <br />
                Videos page: The videos page must display all the videos (the videos must be playable) that the user uploaded in an orderly way, with the functionality to delete and download the videos. <br />
                About Me: The about me page should display a biography along with a picture (image) of yourself (this is helpful as this project will be uploaded to your GitHub repository that you will be able to share down the line). <br />
                All the files you upload (files, images, and videos) should be stored in the main MVC project solution with the following folder structure:  <br />
                > Media <br />
                > Documents <br />
                > Images <br />
                > Videos
            </p>

        </div>
        <div class="col-md-4">
            <h4>Option Selection</h4>
            <p>
                @{
                    if (IsPost)
                    {

                    }
                }

            </p>
            @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <form id="form1" method="post">
                    <div>
                        <table>
                            <tr>
                                <td><p style="font-size:12px">&nbsp;Document&nbsp;</p></td>
                                <td><p style="font-size:12px"><input value="Document" name="uploadType" type="radio" /></p></td>
                            </tr>

                            <tr>
                                <td><p style="font-size:12px">&nbsp;Image&nbsp;</p></td>
                                <td><p style="font-size:12px"><input value="Image" name="uploadType" type="radio" /></p></td>
                            </tr>

                            <tr>
                                <td><p style="font-size:12px">&nbsp;Video&nbsp;</p></td>
                                <td><p style="font-size:12px"><input value="Video" name="uploadType" type="radio" /></p></td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="file" name="files" />
                                    <br />
                                    <input type="submit" value="Upload" />                                    
                                </td>
                            </tr>
                        </table>
                    </div>
                </form>
            }
            </div>
    </div>
</div>

u21429792_HW03/Views/Image/Image.cshtml
@using u21429792_HW03.Models
@model List<FileModel>

@{
    ViewBag.Title = "Image Page";
}

<h2>@ViewBag.Title</h2>

<div>
    <table class="table table-responsive table-bordered" colspan="1" id="table">
        @foreach (FileModel image in Model)
            {
                <tr>
                    <th>
                    <img src="~/images/@image.FileName" width="360" height="240" />
                    <p> @image.FileName </p>
                     <br />
                     <button type="button" class="btn btn-success">@Html.ActionLink("Download", "DownloadImage", new { filename = image.FileName })</button>
                     <button type="button" class="btn btn-danger">@Html.ActionLink("Delete", "DeleteImage", new { filename = image.FileName })</button>
                    </th>
                </tr>
            }            
    </table>
</div>

u21429792_HW03/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Files", "Files", "File")</li>
                    <li>@Html.ActionLink("Image", "Image", "Image")</li>
                    <li>@Html.ActionLink("Video", "Video", "Video")</li>
                    <li>@Html.ActionLink("About Me", "AboutMe", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

u21429792_HW03/Views/Video/Video.cshtml
@using u21429792_HW03.Models
@model List<FileModel>

@{
    ViewBag.Title = "Video Page";
}

<h2>@ViewBag.Title</h2>

<div class="container p-5 my-5 border">
    <table class="table table-responsive table-bordered" colspan="1" id="table">
        @foreach (FileModel video in Model)
        {
            <tr>
                <th>
                    <video autoplay>
                        <source src="~/videos/@video.FileName" type="video/mp4" width="360" height="240" />
                    </video>
                    <p> @video.FileName </p>
                    <br />
                    <button type="button" class="btn btn-success">@Html.ActionLink("Download", "DownloadVideo", new { filename = video.FileName })</button>
                    <button type="button" class="btn btn-danger">@Html.ActionLink("Delete", "DeleteVideo", new { filename = video.FileName })</button>
                </th>
            </tr>
        }
        </table>
</div>